const ts = require('typescript');
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const context = { exports: {} };
vm.runInNewContext(ts.transpileModule(fs.readFileSync('src/crewState.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText, context);
const reduce = context.exports.reduceCrewEvent;
const base = { status: 'running', output: '', activity: [], permissions: [] };
const permission = id => ({ kind: 'permission_request', request_id: id, description: 'write', tool: 'command', input: '{}', suggestions: '', can_remember: false });
let task = reduce(reduce(base, permission('a')), permission('b'));
task = reduce(task, { kind: 'permission_resolved', request_id: 'a', allowed: true, auto: false });
assert.equal(task.status, 'approval');
assert.equal(task.permissions.length, 1);
task = reduce(task, { kind: 'permission_resolved', request_id: 'b', allowed: false, auto: false });
assert.equal(task.status, 'running');
task = reduce(task, { kind: 'message', text: 'result', delta: true });
task = reduce(task, { kind: 'completed', ok: true, summary: '' });
assert.equal(reduce(task, { kind: 'process_exited', code: 0, cancelled: false }).status, 'done');
assert.equal(task.output, 'result');
assert.equal(reduce(base, { kind: 'process_exited', code: 0, cancelled: false }).status, 'failed');
assert.equal(reduce(base, { kind: 'process_exited', code: null, cancelled: true }).status, 'cancelled');
assert.equal(reduce(reduce(base, { kind: 'completed', ok: false, summary: 'quota' }), { kind: 'process_exited', code: 0, cancelled: false }).error, 'quota');
assert.equal(base.output, '');
console.log('PASS crew lifecycle: approvals, completion evidence, cancellation, failure, output');
